import = ["~/.config/alacritty/duality.toml"]

[cursor]
thickness = 0.05

[cursor.style]
shape = "Block"

[font]
size = 14
normal = { family = "JetBrainsMono NL NF Light" }

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
title = "Terminal"
