[registries.crates-io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
#rustflags = ["-C", "link-arg=-fuse-ld=mold", "-Z", "threads=8"]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[unstable]
gc = true
