#!/usr/bin/env python
import shlex
from subprocess import run
from argparse import ArgumentParser


def adb_type(keys: str):
    other_side_cmd = ["input", "text", shlex.quote(keys)]
    here_cmd = ["adb", "shell", " ".join(other_side_cmd)]
    run(here_cmd, text=True, shell=False)


def main():
    parser = ArgumentParser(
        prog="adb-type",
        description="Types the given argument on an Android device.",
        epilog="Needs ADB installed and already connected.",
    )
    parser.add_argument(
        "keys",
        help="What to type, don't forget to use single-quotation marks so your shell doesn't interpret special chars",
    )
    args = parser.parse_args()

    adb_type(args.keys)


if __name__ == "__main__":
    main()
