#!/usr/bin/env python3
import random
import string
import sys


def inspiration(word_length=5, count=None):
    chars = string.ascii_lowercase
    i = 0
    while count == None or i < count:
        yield "".join(random.choices(chars, k=word_length))
        i += 1


def main():
    word_length = sys.argv[1] if len(sys.argv) >= 2 else 5
    try:
        for line in inspiration(word_length=word_length):
            print(line)
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
