#!/usr/bin/env python
import random
import sys


def jumble(reader): 
    output = ""
    for line in reader.readlines():
        for word in line.split():
            mid = list(word[1:-1])
            random.shuffle(mid)
            mid = "".join(mid)
            word = word[0] + mid + word[-1]
            output += word + " "
        output += "\n"
    return output


if __name__ == "__main__":
    print(jumble(sys.stdin))
