#!/bin/sh
screenshot_folder="$HOME/media/pic/screenshot"
moment="$(date --rfc-3339=seconds -u)" &&\
selection="$(slurp)"

grim -g "$selection" "$screenshot_folder/$moment.png" &&\
cp "$screenshot_folder/$moment.png" "$screenshot_folder/unknown.png"
