#!/usr/bin/env python3
import argparse
from pathlib import Path
from typing import Iterator

# fetch yours from
# https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
PORT_NUMBERS = Path.home() / "media" / "tables" / "service-names-port-numbers.csv"


def main():
    parser = argparse.ArgumentParser(
        prog="unused-ports",
        description="Finds ports in the given range that have not been assigned by IANA yet. \n"
        "Note: This does not mean they're not in use.",
    )
    parser.add_argument("start", type=int)
    parser.add_argument("end", type=int)
    args = parser.parse_args()

    inside = range(args.start, args.end)
    for port in unused_ports(inside):
        print(port)


def unused_ports(inside: range) -> Iterator[int]:
    print(inside)

    return []


if __name__ == "__main__":
    main()
